AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Image Recognition Backend

Globals:
  Api:
    EndpointConfiguration: REGIONAL

# Conditions:

# Parameters:

Resources:
  AnalyzeImage:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist
      Handler: AnalyzeImage.handler
      Runtime: nodejs12.x
      Timeout: 30
      MemorySize: 128
      Policies:
        - AmazonRekognitionFullAccess
        - AmazonS3ReadOnlyAccess
      Events:
        AnalyzeImage:
          Type: Api
          Properties:
            Path: /analyze/{imageName}
            Method: get
      Environment:
        Variables:
          IMAGES_BUCKET: !Ref ImagesBucket
  
  ImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        !Join ["-", ["images-bucket", !Ref "AWS::StackName"]]
      AccessControl: Private
      PublicAccessBlockConfiguration:
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        BlockPublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete